# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: Odoo
spec:
    description: |
      Odoo is a suite of open source business apps that cover all your company needs: CRM, eCommerce, accounting, inventory, point of sale, project management, etc.
    icon: https://odoocdn.com/openerp_website/static/src/img/assets/svg/odoo_logo.svg
    variables:
      - key: PUBLIC_DOMAIN
        type: DOMAIN
        name: 網域
        description: 你想將 odoo 綁在哪個網域上？
    tags:
      - CRM
      - ERP
      - CMS
      - eCommerce

    readme: |
      # Odoo
      Odoo is a suite of open source business apps that cover all your company needs: CRM, eCommerce, accounting, inventory, point of sale, project management, etc.
      Odoo's unique value proposition is to be at the same time very easy to use and fully integrated.

      ## Usage
      - Open your browser and go to `https://${PUBLIC_DOMAIN}`
      - Login with the username `admin` and the password you set in the `ODOO_ADMIN_PASSWORD` variable

    services:
      - name: PostgreSQL
        icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
        template: PREBUILT
        spec:
          source:
              image: postgres:15
              command:
                  - docker-entrypoint.sh
                  - -c
                  - config_file=/etc/postgresql/postgresql.conf
          ports:
              - id: database
                port: 5432
                type: TCP
          volumes:
              - id: data
                dir: /var/lib/postgresql/data
          instructions:
              - type: TEXT
                title: Connection String
                content: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${PORT_FORWARDED_HOSTNAME}:${DATABASE_PORT_FORWARDED_PORT}/${POSTGRES_DATABASE}
              - type: TEXT
                title: PostgreSQL Connect Command
                content: psql "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${PORT_FORWARDED_HOSTNAME}:${DATABASE_PORT_FORWARDED_PORT}/${POSTGRES_DATABASE}"
              - type: TEXT
                title: PostgreSQL username
                content: ${POSTGRES_USERNAME}
                category: Credentials
              - type: PASSWORD
                title: PostgresSQL password
                content: ${POSTGRES_PASSWORD}
                category: Credentials
              - type: TEXT
                title: PostgresSQL database
                content: ${POSTGRES_DATABASE}
                category: Credentials
              - type: TEXT
                title: PostgreSQL host
                content: ${PORT_FORWARDED_HOSTNAME}
                category: Hostname & Port
              - type: TEXT
                title: PostgreSQL port
                content: ${DATABASE_PORT_FORWARDED_PORT}
                category: Hostname & Port
          env:
              PGDATA:
                  default: /var/lib/postgresql/data/pgdata
              POSTGRES_CONNECTION_STRING:
                  default: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
                  expose: true
                  readonly: true
              POSTGRES_DATABASE:
                  default: ${POSTGRES_DB}
                  expose: true
                  readonly: true
              POSTGRES_DB:
                  default: odoo
              POSTGRES_HOST:
                  default: ${CONTAINER_HOSTNAME}
                  expose: true
                  readonly: true
              POSTGRES_PASSWORD:
                  default: ${PASSWORD}
                  expose: true
              POSTGRES_PORT:
                  default: ${DATABASE_PORT}
                  expose: true
                  readonly: true
              POSTGRES_URI:
                  default: ${POSTGRES_CONNECTION_STRING}
                  expose: true
                  readonly: true
              POSTGRES_USER:
                  default: odoo-admin
              POSTGRES_USERNAME:
                  default: ${POSTGRES_USER}
                  expose: true
                  readonly: true
          configs:
              - path: /etc/postgresql/postgresql.conf
                template: |
                  # https://github.com/postgres/postgres/blob/master/src/backend/utils/misc/postgresql.conf.sample
                  listen_addresses = '*'
                  max_connections = 100
                  shared_buffers = 128MB
                  dynamic_shared_memory_type = posix
                  max_wal_size = 1GB
                  min_wal_size = 80MB
                  log_timezone = 'Etc/UTC'
                  datestyle = 'iso, mdy'
                  timezone = 'Etc/UTC'
                  lc_messages = 'en_US.utf8'
                  lc_monetary = 'en_US.utf8'
                  lc_numeric = 'en_US.utf8'
                  lc_time = 'en_US.utf8'
                  default_text_search_config = 'pg_catalog.english'
                permission: null
                envsubst: null
      - name: odoo
        icon: https://odoocdn.com/openerp_website/static/src/img/assets/svg/odoo_logo.svg
        template: PREBUILT
        domainKey: PUBLIC_DOMAIN
        spec:
          dependencies:
            - PostgreSQL
          source:
            image: odoo:18.0
          ports:
          - id: web
            port: 8069
            type: HTTP
          env:
            ODOO_DATABASE_MASTER_PASSWORD:
              default: ${PASSWORD}
          volumes:
            - id: odoo-data
              dir: /var/lib/odoo
            - id: odoo-addons
              dir: /mnt/extra-addons
          instructions:
            - type: TEXT
              title: Odoo Database Master Password
              content: ${ODOO_DATABASE_MASTER_PASSWORD}
              category: Credentials
          depends_on:
            - PostgreSQL
          configs:
            - path: /etc/odoo/odoo.conf
              template: |
                [options]
                addons_path = /mnt/extra-addons
                data_dir = /var/lib/odoo
                admin_passwd = ${ODOO_DATABASE_MASTER_PASSWORD}
                db_host = ${POSTGRES_HOST}
                db_port = ${POSTGRES_PORT}
                db_name = ${POSTGRES_DATABASE}
                db_user = ${POSTGRES_USERNAME}
                db_password = ${POSTGRES_PASSWORD}
                load_language = zh_TW

                ; csv_internal_sep = ,
                ; db_maxconn = 64
                ; db_template = template1
                ; dbfilter = .*
                ; debug_mode = False
                ; email_from = False
                ; limit_memory_hard = 2684354560
                ; limit_memory_soft = 2147483648
                ; limit_request = 8192
                ; limit_time_cpu = 60
                ; limit_time_real = 120
                ; list_db = True
                ; log_db = False
                ; log_handler = [':INFO']
                ; log_level = info
                ; logfile = None
                ; longpolling_port = 8072
                ; max_cron_threads = 2
                ; osv_memory_age_limit = 1.0
                ; osv_memory_count_limit = False
                ; smtp_password = False
                ; smtp_port = 25
                ; smtp_server = localhost
                ; smtp_ssl = False
                ; smtp_user = False
                ; workers = 0
                ; xmlrpc = True
                ; xmlrpc_interface = 
                ; xmlrpc_port = 8069
                ; xmlrpcs = True
                ; xmlrpcs_interface = 
                ; xmlrpcs_port = 8071
                
              envsubst: true
