# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: PostgreSQL HA (developing)
spec:
  description: |
    High Availability PostgreSQL cluster with Patroni and etcd. Provides automatic failover and replication for production-grade database deployments.
  icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
  coverImage: https://raw.githubusercontent.com/canyugs/zeabur-template/refs/heads/main/postgresql-ha/cover.png
  tags:
    - Database
    - PostgreSQL
    - High Availability
    - Patroni
  variables:
    - key: POSTGRES_SUPERUSER_PASSWORD
      type: PASSWORD
      name: Superuser Password
      description: Password for PostgreSQL superuser (postgres user)
    - key: POSTGRES_REPLICATION_PASSWORD
      type: PASSWORD
      name: Replication Password
      description: Password for PostgreSQL replication user
    - key: POSTGRES_ADMIN_PASSWORD
      type: PASSWORD
      name: Admin Password
      description: Password for PostgreSQL admin user
  readme: |
    # PostgreSQL High Availability Cluster

    This template deploys a highly available PostgreSQL cluster using:
    - **Patroni**: PostgreSQL HA solution with automatic failover
    - **Spilo**: Docker image combining PostgreSQL and Patroni
    - **etcd**: Distributed configuration and service discovery

    ## Architecture

    - 3x etcd cluster nodes for distributed consensus
    - 3x PostgreSQL nodes with Patroni for automatic failover
    - Built-in replication and health monitoring

    ## Connection Information

    Use any of the Patroni nodes to connect to the cluster:
    - **Host**: Use the hostname of patroni1, patroni2, or patroni3
    - **Port**: 5432
    - **Username**: postgres (superuser) or admin
    - **Password**: Check the environment variables in Zeabur dashboard

    Patroni will automatically route connections to the master node.

    ## Features

    - **Automatic Failover**: If the master fails, Patroni automatically promotes a replica
    - **Synchronous Replication**: Data consistency across nodes
    - **Health Monitoring**: REST API on port 8008 for each node
    - **Rolling Updates**: Update nodes without downtime

    ## Management

    Access Patroni REST API for cluster status:
    - `http://patroni1:8008/`
    - `http://patroni2:8008/`
    - `http://patroni3:8008/`

    ## Documentation

    - [Patroni Documentation](https://patroni.readthedocs.io/)
    - [Spilo GitHub](https://github.com/zalando/spilo)
    - [etcd Documentation](https://etcd.io/docs/)

  services:
    - name: etcd1
      icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/etcd/icon/color/etcd-icon-color.svg
      template: PREBUILT
      spec:
        source:
          image: gcr.io/etcd-development/etcd:v3.6.0
        ports:
          - id: client
            port: 2379
            type: TCP
          - id: peer
            port: 2380
            type: TCP
          - id: metrics
            port: 2381
            type: HTTP
        volumes:
          - id: data
            dir: /etcd-data
        env:
          ETCD_NAME:
            default: etcd1
          ETCD_DATA_DIR:
            default: /etcd-data
          ETCD_INITIAL_ADVERTISE_PEER_URLS:
            default: http://etcd1:2380
          ETCD_LISTEN_PEER_URLS:
            default: http://0.0.0.0:2380
          ETCD_LISTEN_CLIENT_URLS:
            default: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS:
            default: http://etcd1:2379
          ETCD_LISTEN_METRICS_URLS:
            default: http://0.0.0.0:2381
          ETCD_INITIAL_CLUSTER:
            default: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
          ETCD_INITIAL_CLUSTER_STATE:
            default: new
          ETCD_INITIAL_CLUSTER_TOKEN:
            default: etcd-cluster-pg-ha

    - name: etcd2
      icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/etcd/icon/color/etcd-icon-color.svg
      template: PREBUILT
      spec:
        source:
          image: gcr.io/etcd-development/etcd:v3.6.0
        ports:
          - id: client
            port: 2379
            type: TCP
          - id: peer
            port: 2380
            type: TCP
          - id: metrics
            port: 2381
            type: HTTP
        volumes:
          - id: data
            dir: /etcd-data
        env:
          ETCD_NAME:
            default: etcd2
          ETCD_DATA_DIR:
            default: /etcd-data
          ETCD_INITIAL_ADVERTISE_PEER_URLS:
            default: http://etcd2:2380
          ETCD_LISTEN_PEER_URLS:
            default: http://0.0.0.0:2380
          ETCD_LISTEN_CLIENT_URLS:
            default: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS:
            default: http://etcd2:2379
          ETCD_LISTEN_METRICS_URLS:
            default: http://0.0.0.0:2381
          ETCD_INITIAL_CLUSTER:
            default: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
          ETCD_INITIAL_CLUSTER_STATE:
            default: new
          ETCD_INITIAL_CLUSTER_TOKEN:
            default: etcd-cluster-pg-ha

    - name: etcd3
      icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/etcd/icon/color/etcd-icon-color.svg
      template: PREBUILT
      spec:
        source:
          image: gcr.io/etcd-development/etcd:v3.6.0
        ports:
          - id: client
            port: 2379
            type: TCP
          - id: peer
            port: 2380
            type: TCP
          - id: metrics
            port: 2381
            type: HTTP
        volumes:
          - id: data
            dir: /etcd-data
        env:
          ETCD_NAME:
            default: etcd3
          ETCD_DATA_DIR:
            default: /etcd-data
          ETCD_INITIAL_ADVERTISE_PEER_URLS:
            default: http://etcd3:2380
          ETCD_LISTEN_PEER_URLS:
            default: http://0.0.0.0:2380
          ETCD_LISTEN_CLIENT_URLS:
            default: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS:
            default: http://etcd3:2379
          ETCD_LISTEN_METRICS_URLS:
            default: http://0.0.0.0:2381
          ETCD_INITIAL_CLUSTER:
            default: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
          ETCD_INITIAL_CLUSTER_STATE:
            default: new
          ETCD_INITIAL_CLUSTER_TOKEN:
            default: etcd-cluster-pg-ha

    - name: patroni1
      icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
      template: PREBUILT
      dependencies:
        - etcd1
        - etcd2
        - etcd3
      spec:
        source:
          image: ghcr.io/zalando/spilo-15:3.2-p1
          command:
            - sh
            - -c
            - |
              # Wrapper to fix ownership after basebackup
              (
                while sleep 10; do
                  if [ -d /home/postgres/pgdata/pgroot ]; then
                    chown -R postgres:postgres /home/postgres/pgdata/pgroot 2>/dev/null || true
                  fi
                done
              ) &
              exec /launch.sh init
        ports:
          - id: database
            port: 5432
            type: TCP
          - id: api
            port: 8008
            type: HTTP
        healthCheck:
          type: HTTP
          port: api
          http:
            path: /health
        volumes:
          - id: data
            dir: /home/postgres/pgdata
        env:
          SCOPE:
            default: pg-ha
          PATRONI_NAME:
            default: patroni1
          PATRONI_RESTAPI_LISTEN:
            default: 0.0.0.0:8008
          PATRONI_RESTAPI_CONNECT_ADDRESS:
            default: ${CONTAINER_HOSTNAME}:8008
          PATRONI_POSTGRESQL_LISTEN:
            default: 0.0.0.0:5432
          PATRONI_POSTGRESQL_CONNECT_ADDRESS:
            default: ${CONTAINER_HOSTNAME}:5432
          PATRONI_SUPERUSER_USERNAME:
            default: postgres
          PATRONI_SUPERUSER_PASSWORD:
            default: ${POSTGRES_SUPERUSER_PASSWORD}
          PATRONI_REPLICATION_USERNAME:
            default: replicator
          PATRONI_REPLICATION_PASSWORD:
            default: ${POSTGRES_REPLICATION_PASSWORD}
          PATRONI_admin_USERNAME:
            default: admin
          PATRONI_admin_PASSWORD:
            default: ${POSTGRES_ADMIN_PASSWORD}
          PGPASSWORD_SUPERUSER:
            default: ${POSTGRES_SUPERUSER_PASSWORD}
          PGPASSWORD_STANDBY:
            default: ${POSTGRES_REPLICATION_PASSWORD}
          PGPASSWORD_ADMIN:
            default: ${POSTGRES_ADMIN_PASSWORD}
          ETCD3_HOSTS:
            default: etcd1:2379,etcd2:2379,etcd3:2379
        instructions:
          - title: Database Host
            content: "${CONTAINER_HOSTNAME}"
          - title: Database Port
            content: "5432"
          - title: Superuser Username
            content: "postgres"
          - title: Superuser Password
            content: "${POSTGRES_SUPERUSER_PASSWORD}"
          - title: Admin Username
            content: "admin"
          - title: Admin Password
            content: "${POSTGRES_ADMIN_PASSWORD}"
          - title: Superuser Connection String
            content: "postgresql://postgres:${POSTGRES_SUPERUSER_PASSWORD}@${CONTAINER_HOSTNAME}:5432/postgres"
          - title: Admin Connection String
            content: "postgresql://admin:${POSTGRES_ADMIN_PASSWORD}@${CONTAINER_HOSTNAME}:5432/postgres"
          - title: Health Check API
            content: "http://${CONTAINER_HOSTNAME}:8008/health"

    - name: patroni2
      icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
      template: PREBUILT
      dependencies:
        - etcd1
        - etcd2
        - etcd3
      spec:
        source:
          image: ghcr.io/zalando/spilo-15:3.2-p1
          command:
            - sh
            - -c
            - |
              # Wrapper to fix ownership after basebackup
              (
                while sleep 10; do
                  if [ -d /home/postgres/pgdata/pgroot ]; then
                    chown -R postgres:postgres /home/postgres/pgdata/pgroot 2>/dev/null || true
                  fi
                done
              ) &
              exec /launch.sh init
        ports:
          - id: database
            port: 5432
            type: TCP
          - id: api
            port: 8008
            type: HTTP
        healthCheck:
          type: HTTP
          port: api
          http:
            path: /health
        volumes:
          - id: data
            dir: /home/postgres/pgdata
        env:
          SCOPE:
            default: pg-ha
          PATRONI_NAME:
            default: patroni2
          PATRONI_RESTAPI_LISTEN:
            default: 0.0.0.0:8008
          PATRONI_RESTAPI_CONNECT_ADDRESS:
            default: ${CONTAINER_HOSTNAME}:8008
          PATRONI_POSTGRESQL_LISTEN:
            default: 0.0.0.0:5432
          PATRONI_POSTGRESQL_CONNECT_ADDRESS:
            default: ${CONTAINER_HOSTNAME}:5432
          PATRONI_SUPERUSER_USERNAME:
            default: postgres
          PATRONI_SUPERUSER_PASSWORD:
            default: ${POSTGRES_SUPERUSER_PASSWORD}
          PATRONI_REPLICATION_USERNAME:
            default: replicator
          PATRONI_REPLICATION_PASSWORD:
            default: ${POSTGRES_REPLICATION_PASSWORD}
          PATRONI_admin_USERNAME:
            default: admin
          PATRONI_admin_PASSWORD:
            default: ${POSTGRES_ADMIN_PASSWORD}
          PGPASSWORD_SUPERUSER:
            default: ${POSTGRES_SUPERUSER_PASSWORD}
          PGPASSWORD_STANDBY:
            default: ${POSTGRES_REPLICATION_PASSWORD}
          PGPASSWORD_ADMIN:
            default: ${POSTGRES_ADMIN_PASSWORD}
          ETCD3_HOSTS:
            default: etcd1:2379,etcd2:2379,etcd3:2379
        instructions:
          - title: Database Host
            content: "${CONTAINER_HOSTNAME}"
          - title: Database Port
            content: "5432"
          - title: Superuser Username
            content: "postgres"
          - title: Superuser Password
            content: "${POSTGRES_SUPERUSER_PASSWORD}"
          - title: Admin Username
            content: "admin"
          - title: Admin Password
            content: "${POSTGRES_ADMIN_PASSWORD}"
          - title: Superuser Connection String
            content: "postgresql://postgres:${POSTGRES_SUPERUSER_PASSWORD}@${CONTAINER_HOSTNAME}:5432/postgres"
          - title: Admin Connection String
            content: "postgresql://admin:${POSTGRES_ADMIN_PASSWORD}@${CONTAINER_HOSTNAME}:5432/postgres"
          - title: Health Check API
            content: "http://${CONTAINER_HOSTNAME}:8008/health"

    - name: patroni3
      icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
      template: PREBUILT
      dependencies:
        - etcd1
        - etcd2
        - etcd3
      spec:
        source:
          image: ghcr.io/zalando/spilo-15:3.2-p1
          command:
            - sh
            - -c
            - |
              # Wrapper to fix ownership after basebackup
              (
                while sleep 10; do
                  if [ -d /home/postgres/pgdata/pgroot ]; then
                    chown -R postgres:postgres /home/postgres/pgdata/pgroot 2>/dev/null || true
                  fi
                done
              ) &
              exec /launch.sh init
        ports:
          - id: database
            port: 5432
            type: TCP
          - id: api
            port: 8008
            type: HTTP
        healthCheck:
          type: HTTP
          port: api
          http:
            path: /health
        volumes:
          - id: data
            dir: /home/postgres/pgdata
        env:
          SCOPE:
            default: pg-ha
          PATRONI_NAME:
            default: patroni3
          PATRONI_RESTAPI_LISTEN:
            default: 0.0.0.0:8008
          PATRONI_RESTAPI_CONNECT_ADDRESS:
            default: ${CONTAINER_HOSTNAME}:8008
          PATRONI_POSTGRESQL_LISTEN:
            default: 0.0.0.0:5432
          PATRONI_POSTGRESQL_CONNECT_ADDRESS:
            default: ${CONTAINER_HOSTNAME}:5432
          PATRONI_SUPERUSER_USERNAME:
            default: postgres
          PATRONI_SUPERUSER_PASSWORD:
            default: ${POSTGRES_SUPERUSER_PASSWORD}
          PATRONI_REPLICATION_USERNAME:
            default: replicator
          PATRONI_REPLICATION_PASSWORD:
            default: ${POSTGRES_REPLICATION_PASSWORD}
          PATRONI_admin_USERNAME:
            default: admin
          PATRONI_admin_PASSWORD:
            default: ${POSTGRES_ADMIN_PASSWORD}
          PGPASSWORD_SUPERUSER:
            default: ${POSTGRES_SUPERUSER_PASSWORD}
          PGPASSWORD_STANDBY:
            default: ${POSTGRES_REPLICATION_PASSWORD}
          PGPASSWORD_ADMIN:
            default: ${POSTGRES_ADMIN_PASSWORD}
          ETCD3_HOSTS:
            default: etcd1:2379,etcd2:2379,etcd3:2379
        instructions:
          - title: Database Host
            content: "${CONTAINER_HOSTNAME}"
          - title: Database Port
            content: "5432"
          - title: Superuser Username
            content: "postgres"
          - title: Superuser Password
            content: "${POSTGRES_SUPERUSER_PASSWORD}"
          - title: Admin Username
            content: "admin"
          - title: Admin Password
            content: "${POSTGRES_ADMIN_PASSWORD}"
          - title: Superuser Connection String
            content: "postgresql://postgres:${POSTGRES_SUPERUSER_PASSWORD}@${CONTAINER_HOSTNAME}:5432/postgres"
          - title: Admin Connection String
            content: "postgresql://admin:${POSTGRES_ADMIN_PASSWORD}@${CONTAINER_HOSTNAME}:5432/postgres"
          - title: Health Check API
            content: "http://${CONTAINER_HOSTNAME}:8008/health"